services:
  db:
    image: postgres:15
    container_name: todo_db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
  app:
    build: .
    container_name: todo_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@todo_db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: always

volumes:
  database:
    driver: local